server:
  port: 8093
spring:
  application:
    name: portal-resume
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#     &allowMultiQueries=true，表示允许批量操作 mybatis-update-list
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)



# 注册Eureka服务
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:10086/eureka

  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.portal.pojo
  mapper-locations: classpath:mybatis/*.xml
#  config-location: classpath:mybatis/mybatis_config.xml

file:
  path: E:/File-all/test/

redis:
  database: 0
  pool:
    max-active: 8
    max-idle: 9
    max-wait: -1
    min-idle: 0
  redis-dev:
    host: 127.0.0.1
    prot: 6379
    password: 123456
    testOnBorrow: false
  redis-test:
    host:
    prot:
    password:
    testOnBorrow: false
  redis-online:
    host:
    prot:
    password:
    testOnBorrow: false

#
##热部署生效
#spring.devtools.restart.enabled: true
##设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
##classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**


