server:
  port: 10086
spring:
  application:
    name: portal-register
  security:
    user:
      name: admin
      password: admin
      roles: SUPERUSER

eureka:
  instance:
    hostname: register
  client:
    service-url:
      defaultZone: http://admin:admin@portal:${server.port}/eureka
#       defaultZone: http://admin:admin@portal:10086/eureka
    register-with-eureka: false # 把自己注册到eureka服务列表
    fetch-registry: false # 拉取eureka服务信息
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔5秒钟，进行一次服务列表的清理